### ISSUE TITLE
Login Error "Client is not enabled for OAuth2.0 flows"

### ISSUE THREAD

**Issue by mrumpf** [arturlr/minecraft-server-dashboard#5]
The login screen is shown but when you hit the "login" button and trace the requests being sent, after three 302 redirects, the flow stops with the error "Client is not enabled for Oauth2.0 flows":
<img width="894" alt="image" src="https://user-images.githubusercontent.com/1191530/193549689-a3642a5b-4633-4a11-82b9-0af7056aae0d.png">

**Comment by mrumpf** [comment]
I found traces that in Terraform/CloudFormation you need to set allowed_oauth_flows_user_pool_client/AllowedOAuthFlowsUserPoolClient to true. See https://stackoverflow.com/a/68883148 but as I'm new to Amplify and Cognito I do not know currently where to configure that in the project nor why it is not configured by default.

**Comment by mrumpf** [comment]
When I describe the user pool client I can see that the flag "AllowedOAuthFlowsUserPoolClient" is set to false:
````
$ aws cognito-idp describe-user-pool-client --user-pool-id eu-central-1_dfdfdfdf --client-id 2p8jll6lop91dsfsdfsdfdsfsd
{
    "UserPoolClient": {
        "UserPoolId": "eu-central-1_dfdfdfdf",
        "ClientName": "minecrb59cd6eb_app_clientWeb",
        "ClientId": "2p8jll6lop91dsfsdfsdfdsfsd",
        "LastModifiedDate": "2022-10-02T23:50:44.061000+02:00",
        "CreationDate": "2022-10-02T12:05:44.384000+02:00",
        "RefreshTokenValidity": 30,
        "TokenValidityUnits": {
            "RefreshToken": "days"
        },
        "SupportedIdentityProviders": [
            "COGNITO",
            "Google"
        ],
        "CallbackURLs": [
            "https://main.d1lnr5h0wofwhn.amplifyapp.com/"
        ],
        "LogoutURLs": [
            "https://main.d1lnr5h0wofwhn.amplifyapp.com/"
        ],
        "AllowedOAuthFlows": [
            "code"
        ],
        "AllowedOAuthScopes": [
            "aws.cognito.signin.user.admin",
            "email",
            "openid",
            "phone",
            "profile"
        ],
        "AllowedOAuthFlowsUserPoolClient": false,
        "EnableTokenRevocation": true,
        "EnablePropagateAdditionalUserContextData": false,
        "AuthSessionValidity": 3
    }
}
````

**Comment by mrumpf** [comment]
When I update the userpool app client with the following command
````
$ aws cognito-idp update-user-pool-client --user-pool-id eu-central-1_dfdfdfdf --client-id 2p8jll6lop91dsfsdfsdfdsfsd \
    --allowed-o-auth-flows-user-pool-client --allowed-o-auth-flows "code" --allowed-o-auth-scopes "phone" "email" \
   "openid" "profile" "aws.cognito.signin.user.admin" --callback-urls "https://main.sdfsdfsdfsdfds.amplifyapp.com/" \
   --logout-urls "https://main.sdfsdfsdfsdfsd.amplifyapp.com/" --supported-identity-providers COGNITO Google
````
The flag "AllowedOAuthFlowsUserPoolClient" is set to "true" and the login works!
I assume that there is a property in the backend's cli-inputs.json missing to set this flag to true. Strange is that I cannot find a flag in the AWS Console UI to set the property, but maybe it is set implicitly when you select one of the values from the dropdown box.

**Comment by arturlr** [comment]
The cognito client is configured via amplify.yaml file. I also noticed that I needed to go to the console and save the configuration again with the same values to make it to work. I am investigating why it is not being saved.

**Comment by arturlr** [comment]
WIll change this line at amplify.yml file. The AllowedOAuthFlowsUserPoolClient is set to false.

- jq -n --arg url $APP_URL '{RefreshTokenValidity:30, TokenValidityUnits:{ RefreshToken:"days" }, SupportedIdentityProviders:[ "Google", "COGNITO" ], CallbackURLs:[ $url ], LogoutURLs:[ $url ], AllowedOAuthFlows:[ "code" ], AllowedOAuthScopes:[ "aws.cognito.signin.user.admin", "phone", "openid", "profile", "email" ], AllowedOAuthFlowsUserPoolClient:false }' > param.json

**Comment by arturlr** [comment]
Pushed change to fix the issue
